### ISSUE TITLE
several deployments

### ISSUE THREAD

**Issue by kmorte** [georgedoescode/splinejs#1]
Hi, i'm trying to deploy several blops, but the animation only works for the last one. If I deploy then one by one, with a fair time distance, I noticed the the previous one just stops moving.

I'm deploying each of them with a different class and that class does get installed in the svg element.

Any idea what may be going on or some tip the dodge the actual logic=?

Thanks!
bty, great library.

**Comment by georgedoescode** [comment]
@kmorte do you have a reduced-case example? Perhaps a CodePen?

**Comment by kmorte** [comment]
Hi George!

this is the implementation I'm doing from your library;

The intention is to deploy three times a dot. From another part I invoke wait(elem, 'one'), wait(elem, 'two') and wait(elem, 'three');
Then I pass to the svg (I also tried to pass it to the path) the string for getting a class.

And then i put that html (the svg) to the element (which is a div);
All logic beneath that is the creation of the blob.

Thanks!

`const wait = (element, nbr) => {

    const html = `
        <svg id="wait" class="${nbr}">
            <defs>
                <linearGradient id="gradient" gradientTransform="rotate(90)">
                    <stop id="gradientStop1" offset="0%" stop-color="var(--startColor)" />
                    <stop id="gradientStop2 " offset="100%" stop-color="var(--stopColor)" />
                </linearGradient>
            </defs>
            <path d="" fill="orange" width="20" height="20"></path>
        </svg>
    `;

    element.innerHTML += html

    // our <path> element
    const path = document.querySelector(`svg#wait.${nbr} path`);
    // used to set our custom property values
    // const root = document.documentElement;

    let hueNoiseOffset = 0;
    let noiseStep = 0.001;

    const simplex = new SimplexNoise();

    const points = createPoints();

    (function animate() {
        path.setAttribute("d", spline(points, 1, true));

        // for every point...
        for (let i = 0; i < points.length; i++) {
            const point = points[i];

            // return a pseudo random value between -1 / 1 based on this point's current x, y positions in "time"
            const nX = noise(point.noiseOffsetX, point.noiseOffsetX);
            const nY = noise(point.noiseOffsetY, point.noiseOffsetY);
            // map this noise value to a new value, somewhere between it's original location -20 and it's original location + 20
            const x = map(nX, -1, 1, point.originX - 20, point.originX + 20);
            const y = map(nY, -1, 1, point.originY - 20, point.originY + 20);

            // update the point's current coordinates
            point.x = x;
            point.y = y;

            // progress the point's x, y values through "time"
            point.noiseOffsetX += noiseStep;
            point.noiseOffsetY += noiseStep;
        }

        const hueNoise = noise(hueNoiseOffset, hueNoiseOffset);
        const hue = map(hueNoise, -1, 1, 0, 360);

        // root.style.setProperty("--startColor", `hsl(${hue}, 100%, 75%)`);
        // root.style.setProperty("--stopColor", `hsl(${hue + 60}, 100%, 75%)`);
        // document.body.style.background = `hsl(${hue + 60}, 75%, 5%)`;

        hueNoiseOffset += noiseStep / 6;

        requestAnimationFrame(animate);
    })();

    function map(n, start1, end1, start2, end2) {
        return ((n - start1) / (end1 - start1)) * (end2 - start2) + start2;
    }

    function noise(x, y) {
        return simplex.noise2D(x, y);
    }

    function createPoints() {
        const points = [];
        // how many points do we need
        const numPoints = 6;
        // used to equally space each point around the circle
        const angleStep = (Math.PI * 2) / numPoints;
        // the radius of the circle
        const rad = 95;

        for (let i = 1; i <= numPoints; i++) {
            // x & y coordinates of the current point
            const theta = i * angleStep;

            const x = 100 + Math.cos(theta) * rad;
            const y = 100 + Math.sin(theta) * rad;

            // store the point's position
            points.push({
                x: x,
                y: y,
                // we need to keep a reference to the point's original point for when we modulate the values later
                originX: x,
                originY: y,
                // more on this in a moment!
                noiseOffsetX: Math.random() * 1000,
                noiseOffsetY: Math.random() * 1000
            });
        }

        return points;
    }

    path.addEventListener("mouseover", () => {
        console.log('kevinkevin');
        noiseStep = 0.0025;
    });

    path.addEventListener("mouseleave", () => {
        noiseStep = 0.001;
    });

}`

**Comment by kmorte** [comment]
Hi!,
seems i fix it... Or just find tge bug,,,
The diference is, i think, the last lines.

Well, i though there were some mechinic in your code that disabled previous blobs...

Sorry!
And thank you very much
I close the issue.
Greate library, bty!

`// IF DOTS ALREADY DEPLOYED, DO NOT REDEPLOY THEM
    const isDots = box.querySelector('div.dots');
    if(isDots) return null

    const html = `
        <svg id="wait" viewBox="0 0 300 300">
            <path d="" fill="orange" width="100%" height="100%"></path>
        </svg>
    `;

    const divWait = document.createElement('div');
    divWait.classList.add('dots');

    for(let i = 0; i < nbr; i++) {

        const div = document.createElement('div');
        div.classList.add('dot');

        divWait.appendChild(div);
        div.innerHTML += html;

        blobEmit(div);

    };

    // OBSERVE FOR WHEN THE GRAPH ARRIVES TO THE divWait PARENT
    const targetNode = box.querySelector(graph)
`
